name: 'LaunchDarkly Deployment Events'
description: 'Send deployment events to LaunchDarkly'

author: 'LaunchDarkly'
branding:
  icon: toggle-right
  color: gray-dark

inputs:
  access-token:
    description: LaunchDarkly access token
    required: true
  project-key:
    description: The project key
    required: true
  environment-key:
    description: The environment key
    required: true
  application-key:
    description: The application key. Defaults to the repo name.
    required: false
    default: GITHUB_REPO_NAME
  version:
    description: The version. Defaults to git SHA (recommended).
    required: false
    default: GITHUB_SHA
  status:
    description: 'Status of deploy. Values: in_progress, success, failure, cancelled, skipped.'
    required: true
  event-metadata:
    description: A JSON object containing metadata about the event
    required: false
    default: '{}'
  deployment-metadata:
    description: A JSON object containing metadata about the deployment
    required: false
    default: '{}'
  base-uri:
    description: 'The base URI for the LaunchDarkly server. Most users should use the default value.'
    required: false
    default: 'https://app.launchdarkly.com'

# Outputs?

runs:
  using: 'node16'
  main: 'dist/index.js'
