# Run test file with command:
#   act -j deploy-success
#   act -j deploy-fail

name: Test
on: push

jobs:
  deploy-success:
    name: Deploying successfully
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notify - deployment started
        uses: ./
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          base-uri: 'https://ld-stg.launchdarkly.com'
          project-key: default
          environment-key: test
          status: in_progress
          event-metadata: '
            {
            "actor": "${{ github.triggering_actor }}",
            "ref_name": "${{ github.ref_name }}",
            "ref_type": "${{ github.ref_type }}"
            }'

      - name: Deploying application
        id: deploy
        run: echo "Deploying the app..."
      - name: Notify - deployment finished
        uses: ./
        if: always()
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          base-uri: 'https://ld-stg.launchdarkly.com'
          project-key: default
          environment-key: test
          status: ${{ steps.deploy.outcome }}

  deploy-fail:
    name: Deploying fails
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notify - deployment started
        uses: ./
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          base-uri: 'https://ld-stg.launchdarkly.com'
          project-key: default
          environment-key: test
          application-key: failing-workflow
          status: in_progress
          event-metadata: '
            {
            "actor": "${{ github.triggering_actor }}",
            "ref_name": "${{ github.ref_name }}",
            "ref_type": "${{ github.ref_type }}"
            }'

      - name: Deploying application
        id: deploy
        continue-on-error: true
        run: |
          echo "Deploying the app..."
          exit 1
      - name: Notify - deployment finished
        uses: ./
        if: always()
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          base-uri: 'https://ld-stg.launchdarkly.com'
          project-key: default
          environment-key: test
          application-key: failing-workflow
          status: ${{ steps.deploy.outcome }}
